import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '@/components/navbar/Navbar'
import ModalProvider from '@/components/modal/ModalProvider'
import { ThemeProvider } from '@/components/providers/ThemeProvider'
import { cn } from '@/lib/utils'
import ToasterProvider from '@/components/toaster-provider/ToasterProvider'

const font = Lato({ subsets: ['latin'], weight: '700' })

export const metadata: Metadata = {
    title: 'Cash Control - Manage Cash',
    description: 'Generated by create next app',
}

export default function ManageCashLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div>
            <ModalProvider />
            <ToasterProvider />
            {children}
        </div>
    )
}
