import './globals.css'
import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '@/components/navbar/Navbar'
import ModalProvider from '@/components/modal/ModalProvider'
import { ThemeProvider } from '@/components/providers/ThemeProvider'
import { cn } from '@/lib/utils'

const font = Lato({ subsets: ['latin'], weight: '700' })

export const metadata: Metadata = {
  title: 'Cash Control',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={
          cn(
            font.className,
            'bg-white dark:bg-[#313338]'
          )
        }>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey='ChatAppTheme'
          >
            <ModalProvider />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
